name: logger
description: Small, easy to use and extensible logger which prints beautiful logs.
version: 2.0.4
repository: https://github.com/Bungeefan/logger

environment:
  sdk: ">=3.3.4 <4.0.0"

dev_dependencies:
  test: ^1.16.8
  lints: ^2.0.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
